Zubietxe\PrincipalBundle\Entity\Pei:
    type: entity
    table: pei
    indexes:
        id_unico:
            columns:
                - id_unico
    id:
        idPei:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_pei
            generator:
                strategy: IDENTITY
    fields:
        idPeiUnico:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: id_pei_unico
        fechaCreacion:
            type: datetime
            nullable: false
            comment: ''
            column: fecha_creacion
        dimension:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        objetivo:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        meta:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        accion:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        tarea:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        recurso:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        fechaIni:
            type: date
            nullable: true
            comment: ''
            column: fecha_ini
        fechaFin:
            type: date
            nullable: true
            comment: ''
            column: fecha_fin
        responsable:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        resultado:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
    manyToOne:
        idUnico:
            targetEntity: Persona
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_unico:
                    referencedColumnName: id_unico
            orphanRemoval: false
    lifecycleCallbacks: {  }
