Zubietxe\PrincipalBundle\Entity\Varios:
    type: entity
    table: varios
    id:
        idVarios:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_varios
            generator:
                strategy: IDENTITY
    fields:
        variable:
            type: string
            nullable: true
            length: 30
            fixed: false
            comment: ''
        valor:
            type: string
            nullable: true
            length: 30
            fixed: false
            comment: ''
        valor2:
            type: string
            nullable: true
            length: 30
            fixed: false
            comment: ''
        fechaCambio:
            type: datetime
            nullable: true
            comment: ''
            column: fecha_cambio
    lifecycleCallbacks: {  }
