Zubietxe\PrincipalBundle\Entity\Causas:
    type: entity
    table: causas
    id:
        idCausa:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_causa
            generator:
                strategy: IDENTITY
    fields:
        idUnico:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: id_unico
        organoJudicial:
            type: string
            nullable: true
            length: 30
            fixed: false
            comment: ''
            column: organo_judicial
        situacion:
            type: string
            nullable: true
            length: 30
            fixed: false
            comment: ''
        abogado:
            type: string
            nullable: true
            length: 30
            fixed: false
            comment: ''
        citaciones:
            type: string
            nullable: true
            length: 30
            fixed: false
            comment: ''
        condena:
            type: string
            nullable: true
            length: 30
            fixed: false
            comment: ''
        informes:
            type: string
            nullable: true
            length: 30
            fixed: false
            comment: ''
        domicilio:
            type: string
            nullable: true
            length: 30
            fixed: false
            comment: ''
        informes2:
            type: string
            nullable: true
            length: 30
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
