Zubietxe\PrincipalBundle\Entity\Servicios:
    type: entity
    table: servicios
    id:
        idServicio:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_servicio
            generator:
                strategy: IDENTITY
    fields:
        codigo:
            type: string
            nullable: true
            length: 20
            fixed: false
            comment: ''
        nombre:
            type: string
            nullable: true
            length: 30
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
